#!/bin/bash

# one liner from stack overflow that gets the
# full resident directory path of this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# The above allows us to run this script from most anywhere as a program
# If something breaks, uncomment the diagnostic echo and check
# Stack Overflow for more ideas.  There were also elaborate multi-line
# solutions to handle various edge-cases
#echo $SCRIPT_DIR


OPTS="-p$SCRIPT_DIR/?.t -p$SCRIPT_DIR/?.lua"
LISZT_RUNTIME=$SCRIPT_DIR/runtime/libsingle_runtime.so
#echo $OPTS

if [ $1 ] && [ $1 == "-v" ];
then
	if [ $2 ]; then
		LISZT_RUNTIME=$LISZT_RUNTIME $SCRIPT_DIR/terra/terra -vv $OPTS $SCRIPT_DIR/compiler/launch_script.t $2
	else
		LISZT_RUNTIME=$LISZT_RUNTIME $SCRIPT_DIR/terra/terra -vv $OPTS
	fi
else
	if [ $1 ]; then
		LISZT_RUNTIME=$LISZT_RUNTIME $SCRIPT_DIR/terra/terra  $OPTS $SCRIPT_DIR/compiler/launch_script.t $1
	else
		LISZT_RUNTIME=$LISZT_RUNTIME $SCRIPT_DIR/terra/terra  $OPTS
	fi
fi
