#!/usr/bin/env python
#
# This script launches a Liszt program, optionally with Legion.
# For details on usage, run liszt_with_legion --help

import os, platform, subprocess, sys
from optparse import OptionParser
import re

script_dir = os.path.dirname(os.path.realpath(__file__))
terra_opts = ['-p%s/?.t' % script_dir,'-p%s/?.lua' % script_dir]
liszt_runtime = os.path.join(script_dir, 'runtime/libsingle_runtime.so')

parser = OptionParser()
parser.add_option('-v', '--verbose', action='store_true',
        dest='verbose', default=False,
        help='run terra interpreter with verbose option')
parser.add_option('-f', '--file',
        dest='filename',
        help='file containing liszt application')
parser.add_option('-c', '--config',
        dest='config',
        help='file containing installation directory names')

(options, args) = parser.parse_args()

file_opt = []
if options.filename:
    file_opt = [os.path.join(os.getcwd(), options.filename)]

home_dir = os.path.dirname(script_dir)
terra_dir = os.path.join(script_dir, 'terra')
legion_dir = os.path.join(home_dir, 'legion')

if options.config:
    lines = open(options.config)
    for line in lines:
        words = re.split('[\s :]*', line)
        if words[0] == 'terra_dir':
            terra_dir = words[1]
        if words[0] == 'legion_dir':
            legion_dir = words[1]

legion_lang_dir = os.path.join(legion_dir, 'language')
legion_runtime_dir = os.path.join(legion_dir, 'runtime')
legion_bindings_dir = os.path.join(legion_dir, 'bindings', 'terra')

terra_path = [
        '?.lua',
        '?.t',
        os.path.join(legion_dir, 'src', '?.t'),
        os.path.join(terra_dir, 'tests', 'lib', '?.t'),
        os.path.join(legion_bindings_dir, '?.lua'),
        os.path.join(legion_bindings_dir, '?.t'),
        ]

include_path = [
        legion_bindings_dir,
        legion_runtime_dir,
        script_dir,
        ]

lib_path = [
        os.path.join(terra_dir, 'build'),
        legion_bindings_dir,
        ]

os_name = platform.system()
if os_name == 'Darwin':
    LD_LIBRARY_PATH = 'DYLD_LIBRARY_PATH'
else:
    LD_LIBRARY_PATH = 'LD_LIBRARY_PATH'

terra_exe = os.path.join(terra_dir, 'terra')
terra_env = dict(os.environ.items() + [
    ('TERRA_PATH', ';'.join(terra_path)),
    (LD_LIBRARY_PATH, ':'.join(lib_path)),
    ('INCLUDE_PATH', ';'.join(include_path))])
launch_script = [os.path.join(script_dir, 'compiler/launch_legion.t')]

try:
  subprocess.check_call([terra_exe] + launch_script + file_opt, env = terra_env)
except:
    e = sys.exc_info()[0]
    print("Error running liszt with legion :\n%s" % e)
