
# Run the appropriate command in here to build a shared object for tutorial 11

dummy:
	# don't do anything

osx_11:
	gcc -shared -o 11___c_obj.so -I../../include 11___c_code.c

clean:
	-rm 11___c_obj.so
